### ISSUE TITLE
Can we make the repo title all lowercase?

### ISSUE THREAD

**Issue by josephfusco** [mx3m/hikari-for-jekyll#40]
It just really bothers me haha.

proposing `hikari-for-jekyll`

:beer:

**Comment by mx3m** [comment]
Ok you got it!

**Comment by josephfusco** [comment]
fantastic! :beers: :beers: :beers:

**Comment by josephfusco** [comment]
Oh no! It broke the demo site! http://mx3m.github.io/hikari-for-jekyll/

**Comment by mx3m** [comment]
Yeah just realised that too! :D

**Comment by mx3m** [comment]
Im going to fix it, hold on :+1:

**Comment by mx3m** [comment]
gh-pages was basically just an old dist (public?) folder that I had to hardcode cause the demo site wasn't working at the time. Now everything works just fine so I just branched a new gh-pages based on master.

**Comment by josephfusco** [comment]
nice. good work my friend :+1:
